### ISSUE TITLE
Gather information about build configuration of our TensorFlow builds

### ISSUE THREAD

**Issue by fridex** [thoth-station/amun-hwinfo#8]
As of now we provide build information - information about build-time configuration of our TensorFlow wheel files. This file is present as a YAML file inside ``tensorflow-{tensorflow.__version__}.dist-info/build_info.yaml`` file. As this information can be used inside a feature vector when predicting performance/issues of tensorflow builds, we would like to automatically gather this information and provide it in the resulting JSON file of Amun's inspections.

As we currently use YAML as output format, this is currently not that straightforward - we require minimal runtime/buildtime environment stating only dependencies that are needed. We should switch from YAML to JSON (as JSON is in standard Python library) and load it inside amun-hwinfo init-container automatically.

**Comment by fridex** [comment]
@sub-mod

**Comment by sub-mod** [comment]
@fridex This is fixed for new builds.the latest builds all have a json file. 
check https://github.com/AICoE/tensorflow-wheels/releases/download/tf-serving-r1.10-cpu-2018-12-13_154216/build_info.json
I need retrigger older builds of 1.9 1.10 to get the json files.

**Comment by fridex** [comment]
@sub-mod awesome! Please let me in advance when you will plan to do that (please do it after devconf, we will need to erase our database and run initial ingestion again so we have correct digests available). Thanks!

**Comment by sub-mod** [comment]
ACK, lets keep this open till then.

**Comment by goern** [comment]
Can we turn this into a backlog trello card and close the issue?

**Comment by fridex** [comment]
We have implemented this one, PI gather this info. I think this can be closed now.
